-- Add up migration script here
CREATE TABLE board (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    datetime_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(128) NOT NULL UNIQUE
);


CREATE TABLE board_member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    datetime_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    board_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_owner BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (board_id) REFERENCES board(id),
    FOREIGN KEY (user_id) REFERENCES user(id)
);
